import fs from "fs";
import path from "path";

const LOCALES_DIR = String.raw`C:\Users\callz\OneDrive\Documents\My Projects\SynologyDrive\Websites\CareNet 2\src\locales`;
const OPENROUTER_API_KEY =
  "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";

const LANGUAGES = {
  am: "Amharic",
  ar: "Arabic",
  da: "Danish",
  de: "German",
  el: "Greek",
  es: "Spanish",
  fa: "Persian/Farsi",
  fi: "Finnish",
  fr: "French",
  gu: "Gujarati",
  he: "Hebrew",
  hi: "Hindi",
  id: "Indonesian",
  it: "Italian",
  ja: "Japanese",
  kn: "Kannada",
  ko: "Korean",
  ml: "Malayalam",
  mr: "Marathi",
  ms: "Malay",
  my: "Burmese/Myanmar",
  ne: "Nepali",
  nl: "Dutch",
  no: "Norwegian",
  pa: "Punjabi",
  pl: "Polish",
  pt: "Portuguese",
  ru: "Russian",
  si: "Sinhala",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  ur: "Urdu",
  vi: "Vietnamese",
  zh: "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  zu: "Zulu",
};

// English source files — embedded so the script is fully self-contained
const EN_FILES = {
  "common.json": {
    a11y: {
      bottomNav: "Bottom navigation",
      closeMenu: "Close menu",
      closeSidebar: "Close sidebar",
      mainContent: "Main content",
      messages: "Messages",
      notifications: "Notifications",
      openMenu: "Open menu",
      roleNav: "Role navigation",
      sidebarNav: "Sidebar navigation",
      skipToContent: "Skip to main content",
      switchToDark: "Switch to dark mode",
      switchToLight: "Switch to light mode",
      unreadMessages_one: "",
      unreadMessages_other: "",
      unreadNotifications_one: "",
      unreadNotifications_other: "",
    },
    admin: {
      contractsOverview: {
        activeContracts: "Active Contracts",
        allStatus: "All Status",
        allTypes: "All Types",
        inNegotiation: "In Negotiation",
        platformRevenue: "Platform Revenue (Fees)",
        subtitle: "Monitor all contracts, negotiations, and platform revenue",
        title: "Contracts Overview",
        totalContractValue: "Total Contract Value",
      },
      walletManagement: {
        allWallets: "All Wallets",
        creditDonate: "Credit / Donate Points",
        creditDonateDesc: "Give bonus, registration credit, or promo points",
        defaultCommission: "Default Commission",
        freezeWallet: "Freeze Entire Wallet",
        frozenWithheld: "Frozen / Withheld",
        pendingDues: "Pending Dues (Platform Fees)",
        platformFeeDefaults: "Platform Fee Defaults",
        pointConversion: "Point Conversion",
        reasons: {
          chargeback: "Chargeback",
          compensation: "Service Compensation",
          dueClearance: "Platform Fee Due Clearance",
          fraudPrevention: "Fraud Prevention Freeze",
          goodwill: "Goodwill Gesture",
          other: "Other",
          paymentHold: "Payment Hold (Dispute)",
          policyViolation: "Policy Violation Penalty",
          promo: "Promotional Credit",
          refund: "Dispute Refund",
          registrationBonus: "Registration Bonus",
        },
        regBonusesGiven: "Registration Bonuses Given",
        saveFeeConfig: "Save Fee Config",
        subtitle: "Manage user wallets, credit/debit points, configure fees",
        title: "Wallet Management",
        totalCirculation: "Total Points in Circulation",
        transactionFee: "Transaction Fee (all parties)",
        unfreezeWallet: "Unfreeze Wallet",
        withholdDebit: "Withhold / Debit Points",
        withholdDebitDesc: "Freeze for payment, due clearance, or other issues",
      },
    },
    agencyBids: {
      accept: "Accept",
      allBids: "All Bids",
      bidExpiredAnnounce: "Bid on contract #{{id}} has expired",
      bidOnContract: "Bid on Contract #{{id}}",
      bidStatusChangedAnnounce: "Bid #{{id}} status changed to {{status}}",
      bidWithdrawn: "Bid withdrawn",
      browseRequests: "Browse Requests",
      cancel: "Cancel",
      checkPackages: "Check your packages for details.",
      confirm: "Confirm",
      confirmAcceptDesc:
        "Accepting will lock the contract at the counter-offered terms. This cannot be undone.",
      confirmAcceptTitle: "Accept counter-offer?",
      confirmWithdrawDesc:
        "This action cannot be undone. The agency will no longer be considered for this care request.",
      confirmWithdrawTitle: "Withdraw this bid?",
      counter: "Counter",
      counterAccepted: "Counter-offer accepted! Contract locked.",
      counterAcceptFailed: "Failed to accept counter",
      countered: "Countered",
      counterOfferReceivedAnnounce: "Counter-offer received on bid #{{id}}",
      counterPlaceholder: "Your counter message...",
      counterRejected: "Counter-offer rejected. Bid withdrawn.",
      counterRejectFailed: "Failed to reject counter",
      daysAgo: "{{count}}d ago",
      daysAgo_one: "{{count}}d ago",
      daysAgo_other: "{{count}}d ago",
      decline: "Decline",
      dLeft: "{{count}}d left",
      dLeft_one: "{{count}}d left",
      dLeft_other: "{{count}}d left",
      expired: "Expired",
      guardianCounterOffer: "Guardian sent a counter offer",
      hLeft: "{{count}}h left",
      hLeft_one: "{{count}}h left",
      hLeft_other: "{{count}}h left",
      hoursAgo: "{{count}}h ago",
      hoursAgo_one: "{{count}}h ago",
      hoursAgo_other: "{{count}}h ago",
      justNow: "Just now",
      level: "Level {{level}}",
      levelLabel: "Level {{level}}",
      lost: "Lost",
      metCount: "{{met}}/{{total}} met",
      needResponse: "Need Response",
      newBidReceivedAnnounce: "New bid received on care request #{{id}}",
      newSubscriber:
        'New subscriber! A guardian just subscribed to "{{title}}"',
      noBidsFilter: "No {{status}} bids",
      noBidsYet: "No bids submitted yet",
      pending: "Pending",
      proposed: "Proposed",
      responseFailed: "Failed to send response",
      responseSent: "Response sent to guardian",
      score: "Score: {{score}}%",
      scoreLabel: "Score: {{score}}%",
      statusAccepted: "Accepted",
      statusCountered: "Countered",
      statusExpired: "Expired",
      statusPending: "Pending",
      statusRejected: "Rejected",
      statusWithdrawn: "Withdrawn",
      submitted: "Submitted {{time}}",
      subtitle: "Track and manage all your marketplace bids",
      title: "Bid Management",
      totalBids: "Total Bids",
      viewRequest: "View Request",
      winRate: "Win Rate",
      withdraw: "Withdraw",
      withdrawFailed: "Failed to withdraw bid",
      withdrawn: "Withdrawn",
      won: "Won",
    },
    app: { name: "CareNet", tagline: "Trusted Care, Connected Community" },
    bottomNav: {
      analytics: "Analytics",
      back: "Back",
      caregivers: "Caregivers",
      dashboard: "Dashboard",
      home: "Home",
      jobs: "Jobs",
      logs: "Logs",
      meds: "Meds",
      menu: "Menu",
      messages: "Messages",
      notifications: "Alerts",
      orders: "Orders",
      patients: "Patients",
      payments: "Payments",
      placements: "Placements",
      products: "Products",
      queue: "Queue",
      reports: "Reports",
      requirements: "Requirements",
      schedule: "Schedule",
      search: "Search",
      settings: "Settings",
      shifts: "Shifts",
      shop: "Shop",
      staff: "Staff",
      users: "Users",
      vitals: "Vitals",
    },
    btn: {
      apply: "Apply",
      back: "Back",
      cancel: "Cancel",
      clear: "Clear",
      clearAll: "Clear All",
      close: "Close",
      confirm: "Confirm",
      create: "Create",
      delete: "Delete",
      done: "Done",
      edit: "Edit",
      filter: "Filters",
      loadMore: "Load More",
      next: "Next",
      retry: "Retry",
      save: "Save",
      search: "Search",
      submit: "Submit",
      update: "Update",
      view: "View",
    },
    common: { cancel: "Cancel", confirm: "Confirm" },
    connectivity: {
      heartbeat: {
        lost: "Realtime channel lost",
        reconnecting: "Reconnecting...",
        recovered: "Realtime channel recovered",
        stale: "Channel inactive — checking...",
      },
      offline: {
        dismiss: "Dismiss",
        pendingChanges: "{{count}} pending change",
        pendingChanges_one: "",
        pendingChanges_other: "{{count}} pending changes",
        queued: "{{count}} queued",
        queued_one: "",
        queued_other: "",
        retry: "Retry",
        syncedSuccess: "{{count}} item synced successfully",
        syncedSuccess_one: "",
        syncedSuccess_other: "{{count}} items synced successfully",
        syncFailure: "{{count}} sync failure",
        syncFailure_one: "",
        syncFailure_other: "{{count}} sync failures",
        syncingItems: "Syncing {{count}} item...",
        syncingItems_one: "",
        syncingItems_other: "Syncing {{count}} items...",
        waitingToSync: "{{count}} item waiting to sync",
        waitingToSync_one: "",
        waitingToSync_other: "{{count}} items waiting to sync",
        youreOffline: "You're offline",
      },
      realtime: {
        connected: "Connected",
        connecting: "Connecting",
        disconnected: "Disconnected",
        probeBackoff: "Probe every {{interval}}",
        sublabelEstablishing: "Establishing channel...",
        sublabelMock: "Mock (local)",
        sublabelNoSubs: "No active subscriptions",
        sublabelSupabase: "Supabase Realtime",
      },
      retry: {
        attempt: "attempt {{attempt}}",
        nextIn: "next in {{seconds}}s",
        reconnected: "Reconnected",
        requests: "{{count}} requests",
        requests_one: "",
        requests_other: "",
        retrying: "Retrying",
      },
      subscriptionBadge: {
        healthy: "Live",
        lost: "Disconnected",
        stale: "Checking...",
      },
      toast: {
        channelDead: "{{label}} — connection lost",
        channelDeadDesc: "Real-time updates paused. Attempting to reconnect...",
        channelRecovered: "{{label}} — reconnected",
        channelRecoveredDesc: "Real-time updates are flowing again.",
        channelStale: "{{label}} — checking connection...",
        channelStaleDesc:
          "No data received recently. Verifying channel health.",
        multiChannelDead: "{{count}} channels — connections lost",
        multiChannelDead_one: "{{count}} channels — connections lost",
        multiChannelDead_other: "{{count}} channels — connections lost",
        multiChannelDeadDesc:
          "Multiple real-time feeds are down. Attempting to reconnect...",
        multiChannelRecovered: "{{count}} channels — reconnected",
        multiChannelRecovered_one: "{{count}} channels — reconnected",
        multiChannelRecovered_other: "{{count}} channels — reconnected",
        multiChannelRecoveredDesc: "All affected data feeds are flowing again.",
        multiChannelStale: "{{count}} channels — checking connections...",
        multiChannelStale_one: "{{count}} channels — checking connections...",
        multiChannelStale_other: "{{count}} channels — checking connections...",
        multiChannelStaleDesc:
          "Multiple data feeds have gone quiet. Verifying health.",
      },
    },
    contracts: {
      accepted: "Accepted",
      acceptOffer: "Accept Offer",
      actionRequired: "Action Required",
      active: "Active",
      agencyCaregiver: "Agency ↔ Caregiver",
      agreedRate: "Agreed Rate",
      awaitingResponse: "Awaiting response",
      belowListed: "below listed",
      cancelled: "Cancelled",
      completed: "Completed",
      counterOffer: "Counter Offer",
      counterOfferReceived: "Counter-offer received",
      dailyRate: "Daily Rate (CarePoints)",
      disputed: "Disputed",
      duration: "Duration",
      feeBreakdown: "Platform Fee Breakdown",
      financialTerms: "Financial Terms",
      guardianAgency: "Guardian ↔ Agency",
      listedRate: "Listed Rate",
      makeOffer: "Make Offer",
      message: "Message",
      negotiating: "Negotiating",
      negotiationHistory: "Negotiation History",
      newRequirement: "New Requirement",
      offered: "Offered",
      offers: "offers",
      pending: "Pending",
      rejectOffer: "Reject",
      saved: "saved",
      sendOffer: "Send Offer",
      title: "Contracts",
      toasts: {
        loadFailed: "Failed to load contracts",
        newOffer: "New offer received!",
        newOfferDesc: "{{name}}: {{rate}}/day",
        newOfferOnContract: "New offer on this contract!",
        offerAccepted: "Offer accepted!",
        offerAcceptFailed: "Failed to accept offer",
        offerRejected: "Offer rejected",
        offerRejectFailed: "Failed to reject offer",
        offerSubmitFailed: "Failed to submit offer",
        offerSubmitted: "Offer submitted!",
        offerSubmittedDesc: "{{rate}}/day for {{days}} days",
        termsFinalized: "Contract terms finalized",
        updated: "Contract updated",
        updatedDesc: "{{id}} — {{status}}",
        updatedRealtime: "Contract updated in real-time",
      },
      totalPlatformRevenue: "Total Platform Revenue",
      totalValue: "Total Value",
    },
    currency: {
      bdt: "BDT",
      carePoints: "CarePoints",
      conversionRate: "10 CP = ৳ 1",
      cpShort: "CP",
      symbol: "৳",
    },
    empty: {
      noData: "No data available",
      noMessages: "No messages yet",
      noNotifications: "No notifications",
      noResults: "No results found",
    },
    error: {
      forbidden: "You don't have permission to access this page",
      generic: "Something went wrong. Please try again.",
      goHome: "Go Home",
      network: "No internet connection. Check your connection and try again.",
      notFound: "Page not found",
      notFoundMessage:
        "The page you're looking for doesn't exist or has been moved.",
      notFoundTitle: "404",
      unauthorized: "Please log in to continue",
    },
    footer: {
      madeWith: "Made with care in Bangladesh",
      privacy: "Privacy Policy",
      rights: "All rights reserved",
      support: "Support",
      terms: "Terms of Service",
    },
    home: {
      contact: {
        emailLabel: "Email",
        emailNow: "Email Now",
        hotline: "Hotline",
        sendSms: "Send SMS",
        title: "Need Help?",
      },
      features: {
        agency: {
          description:
            "Licensed, high-performing agencies with proven reliability and compliance standards.",
          title: "Vetted Agency Network",
        },
        platform: {
          description:
            "Discover, book, manage, communicate, pay, and track—everything from one powerful dashboard.",
          title: "Single Integrated Platform",
        },
        sectionTitle: "Why CareNet?",
        tracking: {
          description:
            "Full visibility into caregiver schedules and service delivery—bringing transparency and accountability.",
          title: "Real-Time Care Tracking",
        },
        verified: {
          description:
            "Background-checked, certified, and trusted professionals—screened through police verification, health checks, and psychological evaluation.",
          title: "Verified Caregivers",
        },
      },
      hero: {
        brand: "CareNet",
        careShop: "Care Shop",
        jobPortal: "Job Portal",
        register: "Register",
        subtitle:
          "Bangladesh's trusted platform for connecting families with verified caregivers and professional agencies",
        tagline: "Quality care, connected",
      },
    },
    language: { bn: "বাংলা", en: "English", switchTo: "Switch to {{lang}}" },
    nav: {
      about: "About",
      contact: "Contact",
      dashboard: "Dashboard",
      features: "Features",
      home: "Home",
      login: "Log In",
      logout: "Log Out",
      messages: "Messages",
      notifications: "Notifications",
      pricing: "Pricing",
      profile: "Profile",
      register: "Register",
      search: "Search",
      settings: "Settings",
    },
    pageTitles: {
      about: "About",
      adminAgencyApprovals: "Admin Agency Approvals",
      adminContracts: "Admin Contracts",
      adminDashboard: "Dashboard",
      adminLanguageManagement: "Admin Language Management",
      adminPayments: "Admin Payments",
      adminPlacementMonitoring: "Admin Placement Monitoring",
      adminReports: "Admin Reports",
      adminSettings: "Admin Settings",
      adminUsers: "Admin Users",
      adminVerifications: "Admin Verifications",
      adminWalletManagement: "Admin Wallet Management",
      agencyBidManagement: "Agency Bid Management",
      agencyCaregivers: "Agency Caregivers",
      agencyClients: "Agency Clients",
      agencyDashboard: "Dashboard",
      agencyDirectory: "Agency Directory",
      agencyJobApplications: "Agency Job Applications",
      agencyMarketplaceBrowse: "Agency Marketplace Browse",
      agencyMessages: "Agency Messages",
      agencyPackageCreate: "Agency Package Create",
      agencyPayments: "Agency Payments",
      agencyPayroll: "Agency Payroll",
      agencyPlacementDetail: "Agency Placement Detail",
      agencyPlacements: "Agency Placements",
      agencyPublicProfile: "Agency Public Profile",
      agencyReports: "Agency Reports",
      agencyRequirementReview: "Agency Requirement Review",
      agencySettings: "Agency Settings",
      agencyStorefront: "Agency Storefront",
      auditLogs: "Audit Logs",
      backupCaregiver: "Backup Caregiver",
      bidReview: "Bid Review",
      billing: "Billing",
      billingInvoiceDetail: "Billing Invoice Detail",
      blogDetail: "Blog Detail",
      blogList: "Blog List",
      bookingWizard: "Booking Wizard",
      branchManagement: "Branch Management",
      career: "Career",
      caregiverAssignedPatients: "Caregiver Assigned Patients",
      caregiverCareNotes: "Caregiver Care Notes",
      caregiverComparison: "Caregiver Comparison",
      caregiverDashboard: "Dashboard",
      caregiverDocuments: "Caregiver Documents",
      caregiverEarnings: "Caregiver Earnings",
      caregiverJobDetail: "Caregiver Job Detail",
      caregiverMedSchedule: "Caregiver Med Schedule",
      caregiverMessages: "Caregiver Messages",
      caregiverPrescription: "Caregiver Prescription",
      caregiverProfile: "Caregiver Profile",
      caregiverPublicProfile: "Caregiver Public Profile",
      caregiverReviews: "Caregiver Reviews",
      caregiverSchedule: "Caregiver Schedule",
      caregiverSearch: "Caregiver Search",
      caregiverShiftPlanner: "Caregiver Shift Planner",
      careLog: "Care Log",
      carePlanTemplate: "Care Plan Template",
      careRequirement: "Care Requirement",
      careRequirements: "Care Requirements",
      cart: "Cart",
      checkout: "Checkout",
      chooseRole: "Choose Your Role",
      clientCarePlan: "Client Care Plan",
      clientIntake: "Client Intake",
      cmsManager: "CMS Manager",
      connectivityDemo: "Connectivity Demo",
      contact: "Contact",
      contactUs: "Contact Us",
      contractDetail: "Contract Detail",
      contractDispute: "Contract Dispute",
      contractList: "Contract List",
      dailyEarningsDetail: "Daily Earnings Detail",
      dashboard: "Dashboard",
      dataPrivacyManager: "Data Privacy Manager",
      disputeAdjudication: "Dispute Adjudication",
      documentVerification: "Document Verification",
      emergencyHub: "Emergency Hub",
      familyHub: "Family Hub",
      features: "Features",
      financialAudit: "Financial Audit",
      forgotPassword: "Forgot Password",
      globalSearch: "Global Search",
      guardianDashboard: "Dashboard",
      guardianMarketplaceHub: "Guardian Marketplace Hub",
      guardianMessages: "Guardian Messages",
      guardianPatients: "Guardian Patients",
      guardianPlacementDetail: "Guardian Placement Detail",
      guardianPlacements: "Guardian Placements",
      guardianProfile: "Guardian Profile",
      guardianReviews: "Guardian Reviews",
      guardianSchedule: "Guardian Schedule",
      handoffNotes: "Handoff Notes",
      helpCenter: "Help Center",
      home: "Home",
      incidentManagement: "Incident Management",
      incidentReport: "Incident Report",
      incidentReportWizard: "Incident Report Wizard",
      invoiceDetail: "Invoice Detail",
      jobApplicationDetail: "Job Application Detail",
      jobManagement: "Job Management",
      jobMarketplace: "Job Marketplace",
      marketplace: "Marketplace",
      medicationReminders: "Medication Reminders",
      merchantAnalytics: "Merchant Analytics",
      merchantFulfillment: "Merchant Fulfillment",
      merchantOnboarding: "Merchant Onboarding",
      messages: "Messages",
      mfaSetup: "MFA Setup",
      mfaVerify: "MFA Verify",
      moderatorContent: "Moderator Content",
      moderatorDashboard: "Dashboard",
      moderatorEscalations: "Moderator Escalations",
      moderatorQueueDetail: "Moderator Queue Detail",
      moderatorReports: "Moderator Reports",
      moderatorReviews: "Moderator Reviews",
      moderatorSanctions: "Moderator Sanctions",
      newCareRequirement: "New Care Requirement",
      notFound: "Not Found",
      notifications: "Notifications",
      orderHistory: "Order History",
      orderSuccess: "Order Success",
      orderTracking: "Order Tracking",
      packageDetail: "Package Detail",
      patientCareHistory: "Patient Care History",
      patientDashboard: "Dashboard",
      patientDocumentUpload: "Patient Document Upload",
      patientHealthReport: "Patient Health Report",
      patientIntake: "Patient Intake",
      patientMedicalRecords: "Patient Medical Records",
      patientMessages: "Patient Messages",
      patientProfile: "Patient Profile",
      patientSchedule: "Patient Schedule",
      payments: "Payments",
      payoutSetup: "Payout Setup",
      policyManager: "Policy Manager",
      portfolioEditor: "Portfolio Editor",
      pricing: "Pricing",
      privacyPolicy: "Privacy Policy",
      productCategory: "Product Category",
      productDetails: "Product Details",
      productEditor: "Product Editor",
      productList: "Product List",
      productReviews: "Product Reviews",
      promoManagement: "Promo Management",
      referenceManager: "Reference Manager",
      refundRequest: "Refund Request",
      register: "Register",
      requirementsInbox: "Requirements Inbox",
      resetPassword: "Reset Password",
      settings: "Settings",
      shiftCheckIn: "Shift Check In",
      shiftDetail: "Shift Detail",
      shiftMonitoring: "Shift Monitoring",
      shiftRating: "Shift Rating",
      shopAnalytics: "Shop Analytics",
      shopDashboard: "Dashboard",
      shopInventory: "Shop Inventory",
      shopOrders: "Shop Orders",
      shopProducts: "Shop Products",
      signIn: "Sign In",
      sitemap: "Sitemap",
      skillsAssessment: "Skills Assessment",
      staffAttendance: "Staff Attendance",
      staffHiring: "Staff Hiring",
      submitPaymentProof: "Submit Payment Proof",
      supportTicketDetail: "Support Ticket Detail",
      systemHealth: "System Health",
      taxReports: "Tax Reports",
      terms: "Terms",
      ticketSubmission: "Ticket Submission",
      topUp: "Top Up",
      trainingPortal: "Training Portal",
      transferHistory: "Transfer History",
      userInspector: "User Inspector",
      verificationCase: "Verification Case",
      verificationResult: "Verification Result",
      verifyPayment: "Verify Payment",
      vitalsTracking: "Vitals Tracking",
      wallet: "Wallet",
      wishlist: "Wishlist",
    },
    sidebar: {
      about: "About",
      agencies: "Agencies",
      agencyApprovals: "Agency Approvals",
      analytics: "Analytics",
      auditLogs: "Audit Logs",
      bidManagement: "Bid Management",
      billing: "Billing",
      blog: "Blog",
      branches: "Branches",
      careers: "Careers",
      caregivers: "Caregivers",
      careHistory: "Care History",
      careLog: "Care Log",
      careNotes: "Care Notes",
      careRequirements: "Care Requirements",
      clientIntake: "Client Intake",
      clients: "Clients",
      cmsManager: "CMS Manager",
      compareCaregivers: "Compare Caregivers",
      contactUs: "Contact Us",
      content: "Content",
      contracts: "Contracts",
      contractsOverview: "Contracts Overview",
      dailyEarnings: "Daily Earnings",
      dashboard: "Dashboard",
      dataPrivacy: "Data Privacy",
      disputes: "Disputes",
      documents: "Documents",
      earnings: "Earnings",
      emergencyHub: "Emergency Hub",
      familyHub: "Family Hub",
      features: "Features",
      financialAudit: "Financial Audit",
      findCaregivers: "Find Caregivers",
      fulfillment: "Fulfillment",
      healthReport: "Health Report",
      helpCenter: "Help Center",
      incidentReport: "Incident Report",
      incidentsList: "Incidents",
      inventory: "Inventory",
      jobManagement: "Job Management",
      languages: "Languages",
      marketplace: "Marketplace",
      marketplaceBrowse: "Browse Marketplace",
      marketplaceHub: "Marketplace Hub",
      medicalRecords: "Medical Records",
      medications: "Medications",
      medSchedule: "Med Schedule",
      merchantAnalytics: "Merchant Analytics",
      messages: "Messages",
      myJobs: "My Jobs",
      myPatients: "My Patients",
      newBooking: "New Booking",
      notifications: "Notifications",
      onboarding: "Onboarding",
      orders: "Orders",
      packageCreate: "Create Package",
      patientIntake: "Patient Intake",
      payments: "Payments",
      payoutSetup: "Payout Setup",
      payroll: "Payroll",
      placements: "Placements",
      policyManager: "Policy Manager",
      portal: "{{role}} Portal",
      portfolio: "Portfolio",
      postRequirement: "Post Requirement",
      prescriptions: "Prescriptions",
      pricing: "Pricing",
      privacyPolicy: "Privacy Policy",
      productEditor: "Product Editor",
      products: "Products",
      profile: "Profile",
      promoManagement: "Promo Management",
      references: "References",
      refundRequest: "Refund Request",
      reports: "Reports",
      requirements: "Requirements",
      reviews: "Reviews",
      schedule: "Schedule",
      searchPlaceholder: "Search...",
      section: {
        browse: "Browse",
        contentConfig: "Content & Config",
        finance: "Finance",
        financeSettings: "Finance & Settings",
        general: "General",
        growth: "Growth",
        health: "Health",
        main: "Main",
        management: "Management",
        operations: "Operations",
        patientCare: "Patient Care",
        privacyBrowse: "Privacy & Browse",
        supportInfo: "Support & Info",
        system: "System",
        tools: "Tools",
      },
      settings: "Settings",
      shiftMonitor: "Shift Monitor",
      shiftPlanner: "Shift Planner",
      shop: "Shop",
      sitemap: "Sitemap",
      skillsAssessment: "Skills Assessment",
      staffAttendance: "Staff Attendance",
      staffHiring: "Staff Hiring",
      storefront: "Storefront",
      submitTicket: "Submit Ticket",
      systemHealth: "System Health",
      taxReports: "Tax Reports",
      termsOfService: "Terms of Service",
      trainingPortal: "Training Portal",
      userInspector: "User Inspector",
      users: "Users",
      verifications: "Verifications",
      vitalsTracking: "Vitals Tracking",
      wallet: "CarePoints Wallet",
      walletManagement: "Wallet Management",
    },
    status: {
      accepted: "Accepted",
      active: "Active",
      approved: "Approved",
      cancelled: "Cancelled",
      completed: "Completed",
      disputed: "Disputed",
      draft: "Draft",
      frozen: "Frozen",
      inactive: "Inactive",
      inProgress: "In Progress",
      late: "Late",
      negotiating: "Negotiating",
      offered: "Offered",
      offline: "Offline",
      online: "Online",
      onTime: "On Time",
      pending: "Pending",
      rejected: "Rejected",
      submitted: "Submitted",
    },
    time: {
      daysAgo: "{{count}}d ago",
      daysAgo_one: "{{count}}d ago",
      daysAgo_other: "{{count}}d ago",
      hoursAgo: "{{count}}h ago",
      hoursAgo_one: "{{count}}h ago",
      hoursAgo_other: "{{count}}h ago",
      minutesAgo: "{{count}}m ago",
      now: "Now",
      thisMonth: "This Month",
      thisWeek: "This Week",
      today: "Today",
      yesterday: "Yesterday",
    },
    undo: {
      actionUndone: "Undone: {{action}}",
      offerAccepted: "offer acceptance",
      offerRejected: "offer rejection",
      offerSubmitted: "offer submission",
      pointsPurchased: "points purchase",
      undoButton: "Undo",
      undoFailed: "Undo failed",
      undoHint: "Press Ctrl+Z to undo",
      withdrawal: "withdrawal",
    },
    upload: {
      browseFiles: "Browse Files",
      camera: "Camera",
      dragDrop: "Drag & drop files here, or",
      maxSize: "Max {{size}}MB",
      rotate: "Rotate",
      uploaded: "Uploaded",
    },
    wallet: {
      all: "All",
      balance: "Available Balance",
      bonus: "bonus",
      buyNow: "Buy Now",
      buyPoints: "Buy Points",
      conversionRate: "Conversion Rate",
      credits: "Credits",
      debits: "Debits",
      exportStatement: "Export Statement",
      feeDetails: "Fee Details",
      feeRate: "Fee Rate",
      fees: "Fees",
      frozen: "frozen",
      pendingDue: "Platform Fee Due",
      perTransaction: "per transaction",
      platformFee: "Platform Fee",
      pointPackages: {
        basic: "Basic",
        enterprise: "Enterprise",
        premium: "Premium",
        standard: "Standard",
        starter: "Starter",
      },
      regBonus: "Reg. Bonus",
      title: "CarePoints Wallet",
      toasts: {
        actionFailed: "Action failed",
        addedToWallet: "+{{amount}} added to wallet",
        balanceChanged: "{{userId}} balance changed",
        balanceUpdated: "Wallet balance updated",
        credited: "Credited {{amount}}",
        creditFailed: "Credit failed",
        debited: "Debited {{amount}}",
        debitFailed: "Debit failed",
        feeUpdated: "Fee config updated",
        feeUpdatedDesc: "Fee: {{fee}}%, Commission: {{commission}}%",
        freezeFailed: "Freeze failed",
        froze: "Froze {{amount}}",
        loadFailed: "Failed to load wallet",
        newBalance: "New balance: {{amount}}",
        pointsDeducted: "Points deducted",
        pointsDeductedDesc: "{{amount}} — {{description}}",
        pointsReceived: "Points received!",
        pointsReceivedDesc: "+{{amount}} — {{description}}",
        purchaseFailed: "Purchase failed",
        purchaseSuccess: "Points purchased successfully!",
        updateFailed: "Update failed",
        walletFrozen: "Wallet frozen",
        walletUnfrozen: "Wallet unfrozen",
        walletUpdated: "Wallet updated",
        withdrawDesc: "{{amount}} → {{method}}",
        withdrawFailed: "Withdrawal failed",
        withdrawInitiated: "Withdrawal initiated",
      },
      totalEarned: "Total Earned",
      totalSpent: "Total Spent",
      totalWithdrawn: "Withdrawn",
      transactionHistory: "Transaction History",
      withdraw: "Withdraw",
      withheldByAdmin: "Withheld by Admin",
    },
  },
  "auth.json": {
    forgotPassword: {
      backToLogin: "Back to Login",
      sendCode: "Send Reset Code",
      subtitle: "Enter your phone number to receive a reset code",
      title: "Reset Password",
    },
    login: {
      demoAccess: "Demo Access",
      demoHint: "Try CareNet with a demo account",
      forgotPassword: "Forgot password?",
      loginBtn: "Log In",
      noAccount: "Don't have an account?",
      orContinue: "or continue with",
      password: "Password",
      phone: "Phone Number",
      phonePlaceholder: "+880 1XXXXXXXXX",
      signUp: "Sign Up",
      subtitle: "Log in to your CareNet account",
      title: "Welcome Back",
    },
    logout: {
      confirm: "Are you sure you want to log out?",
      logoutBtn: "Log Out",
      title: "Log Out",
    },
    mfa: {
      appAuth: "Authenticator App",
      appAuthDesc: "Use Google Authenticator or similar",
      biometric: "Biometric Login",
      biometricDesc: "Use fingerprint or face recognition",
      setupTitle: "Set Up 2FA",
      title: "Two-Factor Authentication",
    },
    otp: {
      callMe: "Call me instead",
      didntReceive: "Didn't receive the code?",
      resend: "Resend Code",
      resendIn: "Resend in {{seconds}}s",
      subtitle: "Enter the 6-digit code sent to {{phone}}",
      title: "Verify Your Phone",
      verify: "Verify",
    },
    register: {
      agreeTerms: "I agree to the Terms of Service and Privacy Policy",
      confirmPassword: "Confirm Password",
      email: "Email (Optional)",
      fullName: "Full Name",
      haveAccount: "Already have an account?",
      password: "Create Password",
      phone: "Phone Number",
      registerBtn: "Create Account",
      signIn: "Sign In",
      subtitle: "Join Bangladesh's trusted care platform",
      title: "Create Account",
    },
    roleSelection: {
      admin: "Administrator",
      adminDesc: "Platform administrator",
      agency: "Agency",
      agencyDesc: "Healthcare staffing agency",
      agencyOwner: "Agency Owner",
      agencyOwnerDesc: "Own and manage a healthcare staffing agency",
      caregiver: "Caregiver",
      caregiverDesc: "Professional care provider",
      continueAs: "Continue as {{role}}",
      guardian: "Guardian",
      guardianDesc: "Family member or legal guardian",
      moderator: "Moderator",
      moderatorDesc: "Content & review moderator",
      patient: "Patient",
      patientDesc: "Care recipient",
      shopOwner: "Shop Owner",
      shopOwnerDesc: "Medical supply vendor",
      subtitle: "Choose how you want to use CareNet",
      title: "Select Your Role",
    },
  },
  "caregiver.json": {
    nav: {
      dashboard: "Dashboard",
      patients: "My Patients",
      jobs: "My Jobs",
      careLog: "Care Log",
      schedule: "Schedule",
      messages: "Messages",
      earnings: "Earnings",
      reviews: "Reviews",
      documents: "Documents",
      profile: "Profile",
    },
    dashboard: {
      welcome: "Welcome back, {{name}}",
      activeShift: "Active Shift",
      todaySchedule: "Today's Schedule",
      upcomingShifts: "Upcoming Shifts",
      recentLogs: "Recent Logs",
      earnings: "Earnings",
    },
    shift: {
      checkIn: "Check In",
      checkOut: "Check Out",
      onTime: "On Time",
      late: "Late",
      gracePeriod: "Grace Period",
      currentShift: "Current Shift",
      shiftDetails: "Shift Details",
      startTime: "Start Time",
      endTime: "End Time",
      duration: "Duration",
    },
    careLog: {
      title: "New Care Log",
      whatLogging: "What are you logging?",
      meal: "Meal",
      medication: "Medication",
      vitals: "Vitals",
      exercise: "Exercise",
      bathroom: "Bathroom",
      sleep: "Sleep",
      observation: "Observation",
      incident: "Incident",
      notes: "Notes",
      save: "Save Care Log",
      saved: "Care Log Saved!",
      logAnother: "Log Another Entry",
      recentLogs: "Recent Logs (This Shift)",
    },
    jobs: {
      available: "Available Jobs",
      applied: "Applied",
      matched: "Matched",
      applyNow: "Apply Now",
      viewDetails: "View Details",
    },
  },
  "guardian.json": {
    bidReview: {
      acceptBid: "Accept Bid",
      agencyMessage: "Agency Message",
      bidAccepted: "Bid accepted! Contract is now locked.",
      bidExpired: "This bid has expired",
      bidRejected: "Bid rejected.",
      bidsReceived: "{{count}} bid(s) received — sorted by compliance score",
      bidsReceived_one: "",
      bidsReceived_other: "",
      budget: "Budget",
      cancel: "Cancel",
      "complianceField_schedule.hours_per_day": "Hours/Day",
      "complianceField_staffing.caregiver_count": "Caregiver Count",
      "complianceField_staffing.required_level": "Staff Level",
      complianceMet: "Met",
      complianceNA: "N/A",
      compliancePartial: "Partial",
      complianceScore: "Compliance Score",
      complianceSection_auto: "Auto-calculated",
      complianceSection_care_needs: "Care Needs",
      complianceSection_schedule: "Schedule",
      complianceSection_staffing: "Staffing",
      complianceUnmet: "Unmet",
      confirm: "Confirm",
      confirmAcceptDesc:
        "Accepting will lock the contract with this agency. Other bids will be automatically rejected.",
      confirmAcceptTitle: "Accept this bid?",
      confirmRejectDesc:
        "This agency will be notified that their bid was rejected. This cannot be undone.",
      confirmRejectTitle: "Reject this bid?",
      counter: "Counter",
      counterOffer: "Counter Offer",
      counterPlaceholder: "Write your counter offer message...",
      counterSent: "Counter offer sent!",
      deviationRemarks: "Deviation Remarks",
      expiresIn: "Expires in {{time}}",
      met: "met",
      noBidsYet:
        "No bids received yet. Agencies will bid on your requirement soon.",
      offered: "Offered",
      partial: "partial",
      rejectBid: "Reject",
      remark: "Remark",
      requestNotFound: "Request not found",
      required: "Required",
      requirementsSummary: "Your Requirements Summary",
      schedule: "Schedule",
      sendCounter: "Send Counter",
      staffCount: "Staff Count",
      staffLevel: "Staff Level",
      statusAccepted: "Accepted",
      statusCounterSent: "Counter Sent",
      statusExpired: "Expired",
      statusRejected: "Rejected",
      statusWithdrawn: "Withdrawn",
      title: "Review Bids",
      total: "total",
      unmet: "unmet",
    },
    dashboard: {
      activePlacements: "Active Placements",
      pendingRequirements: "Pending Requirements",
      recentActivity: "Recent Activity",
      upcomingShifts: "Upcoming Shifts",
      welcome: "Welcome, {{name}}",
    },
    marketplace: {
      activeCare: "Active Care",
      agencyPackages: "Agency Packages",
      allCategories: "All Categories",
      autoExpiryNote:
        "If no expiry is set, your listing automatically expires in 15 days to keep the marketplace fresh. You can always re-post expired jobs from your dashboard.",
      bidExpired: "This bid has expired",
      bidExpiresIn: "Expires in {{time}}",
      confirmSubscription: "Confirm Subscription",
      daysLeft: "{{count}}d left",
      expired: "Expired",
      expiryDaysFromPosting: "{{count}} days from posting",
      extraChargesMayApply: "Extra charges may apply",
      featured: "Featured Package",
      fromPackage: "From Package",
      listingExpiry: "Listing Expiry",
      myPostedJobs: "My Posted Jobs",
      newSubscriber:
        'New subscriber! A guardian just subscribed to "{{title}}"',
      noPackages: "No packages match your search",
      noRequirements: "No care requirements posted yet",
      overtimeRate: "Overtime Rate",
      packageSchedule: "Package Schedule",
      packageSubscription: "Package Subscription",
      platformFee: "Platform Fee",
      postFirst: "Post Your First Requirement",
      postRequirement: "Post Care Requirement",
      prefilledFrom: "Pre-filled from: {{title}}",
      prefilledHint:
        "Service type auto-selected based on package category. You can change it below.",
      receivingBids: "Receiving Bids",
      repostFailed: "Failed to re-post",
      repostSuccess: "Job re-posted to marketplace!",
      repostToMarketplace: "Re-post to Marketplace",
      searchPackages: "Search packages or agencies...",
      serviceGuarantee: "Service Guarantee",
      subscribers: "{{count}} subscribers",
      subtitle: "Post requirements or browse agency packages",
      title: "Care Marketplace",
      totalBids: "Total Bids",
      totalRequests: "Total Requests",
      trialAvailable: "Trial available",
      view: "View",
      viewDetails: "View Details",
    },
    nav: {
      careRequirements: "Care Requirements",
      dashboard: "Dashboard",
      messages: "Messages",
      patients: "My Patients",
      payments: "Payments",
      placements: "Placements",
      profile: "Profile",
      reviews: "Reviews",
      schedule: "Schedule",
      search: "Find Care",
    },
    packageDetail: {
      addOns: "Available Add-ons",
      agency: "Agency",
      attendanceGuarantee: "Attendance Guarantee",
      backgroundVerified: "Background verified",
      backToMarketplace: "Back to Marketplace",
      caregivers: "Caregivers",
      compliance: "Compliance",
      contactAgency: "Contact Agency",
      contractProvided: "Contract provided",
      emergencyResponse: "Emergency Response",
      exclusions: "Exclusions",
      experience: "Experience",
      extraCharges: "Extra Charges",
      hoursPerDay: "Hours/Day",
      level: "Level",
      logistics: "Logistics",
      medicalFit: "Medical fitness certified",
      notFound: "Package not found",
      nurses: "Nurses",
      overtime: "Overtime",
      pattern: "Pattern",
      replacementTime: "Replacement Time",
      reports: "Reports",
      schedule: "Schedule",
      servicesIncluded: "Services Included",
      shift: "Shift",
      sla: "Service Level Agreement",
      staffing: "Staffing",
      subscribe: "Subscribe to Package",
      subscribeThis: "Subscribe to This Package",
      trialAvailable: "Trial period available",
    },
    placement: {
      active: "Active Placements",
      agency: "Agency",
      caregiver: "Caregiver",
      completed: "Completed",
      pending: "Pending",
      startDate: "Start Date",
      viewDetails: "View Details",
    },
    requirement: {
      careType: "Care Type",
      create: "Create Requirement",
      location: "Location",
      schedule: "Schedule",
      specialNeeds: "Special Needs",
      submit: "Submit Requirement",
      title: "Care Requirement",
    },
    search: {
      agencies: "Agencies",
      caregivers: "Browse Caregivers",
      requestViaAgency: "Request via Agency",
      searchPlaceholder: "Search by agency, specialty, or location...",
      submitRequirement: "Submit Care Requirement",
      subtitle:
        "Agencies provide verified caregivers, 24/7 coverage, and guaranteed replacement",
      title: "Find a Care Agency",
      verifiedAgencies: "{{count}} verified agencies",
      viewProfile: "View Agency Profile",
    },
    wizard: {
      additionalNotes: "Additional Notes",
      additionalNotesPlaceholder: "Any other requirements or preferences",
      age: "Age",
      back: "Back",
      backToOptions: "Back to Options",
      browseDesc:
        "Explore pre-built care packages from verified agencies. Compare prices, services, and SLAs — subscribe instantly.",
      browsePackages: "Browse Agency Packages",
      budget: "Budget",
      budgetDesc: "Set your monthly budget range in BDT",
      budgetRange: "Budget Range",
      careRequirements: "Care Requirements",
      careRequirementsDesc: "Select the types of care needed",
      careTypes: "Care Types",
      clearPricing: "Clear pricing",
      createRequirement: "Create Requirement",
      customRequirements: "Custom requirements",
      directOnly: "Direct to selected agency only",
      distribution: "Distribution",
      duration: "Duration",
      durationPlaceholder: "e.g., 3 months, ongoing",
      expiryDays: "{{count}} days",
      expiryDesc: "Your job will auto-expire after this period (max 15 days)",
      expiryNote:
        "If no expiry is set, your listing automatically expires in 15 days to keep the marketplace fresh. You can always re-post expired jobs from your dashboard.",
      exploreFirst:
        "We recommend exploring existing agency packages first — you might find exactly what you need!",
      exploreMarketplace: "Explore Marketplace",
      findRightCare: "Find the Right Care",
      for: "for",
      instantBooking: "Instant booking",
      listingExpiry: "Listing Expiry",
      marketplaceHint:
        "Multiple agencies can submit competitive bids. You choose the best offer.",
      marketplaceOff: "Only the selected agency will see this requirement",
      marketplaceOn: "Agencies can discover and bid on your requirement",
      maximum: "Maximum (৳)",
      medicalConditions: "Medical Conditions",
      medicalConditionsPlaceholder:
        "Describe any medical conditions, allergies, or special needs",
      minimum: "Minimum (৳)",
      negotiateTerms: "Negotiate terms",
      next: "Next",
      notSpecified: "Not specified",
      openMarketplace: "Posted to Open Marketplace (agencies can bid)",
      patient: "Patient",
      patientInfo: "Patient Information",
      patientName: "Patient Name",
      patientNamePlaceholder: "Full name of care recipient",
      perMonth: "/month",
      postDesc:
        "Create a detailed care requirement and let agencies bid on it, or send directly to a specific agency.",
      postRequirement: "Post a Care Requirement",
      postToMarketplace: "Post to Marketplace",
      preferredStartDate: "Preferred Start Date",
      receiveBids: "Receive bids",
      recommended: "Recommended",
      reviewSubmit: "Review & Submit",
      schedule: "Schedule",
      schedulePreferences: "Schedule Preferences",
      selectAgency: "Select an Agency",
      selectAgencyDesc:
        "Choose a trusted care agency to handle your requirement",
      starting: "starting",
      submitFailed: "Failed to submit requirement. Please try again.",
      submitMarketplaceSuccess: "Care requirement posted to marketplace!",
      submitRequirement: "Submit Requirement",
      submitSuccess: "Care requirement submitted!",
      submitting: "Submitting...",
      verifiedAgencies: "Verified agencies",
    },
  },
};

async function translateFile(enContent, langCode, langName) {
  const prompt = `Translate the following JSON object values into ${langName} (language code: ${langCode}).
Rules:
- Keep ALL JSON keys exactly as-is
- Only translate the string values
- Keep "CareNet" as-is (brand name, never translate it)
- Keep {{variable}} placeholders exactly as-is (e.g. {{count}}, {{name}}, {{role}})
- Keep empty strings as empty strings
- Keep symbols like ৳, ↔, +880 as-is
- Return ONLY valid JSON, no markdown fences, no explanation

JSON:
${JSON.stringify(enContent, null, 2)}`;

  const response = await fetch(
    "https://openrouter.ai/api/v1/chat/completions",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
        "HTTP-Referer": "https://carenet.app",
        "X-Title": "CareNet Translation",
      },
      body: JSON.stringify({
        model: "arcee-ai/trinity-large-preview:free",
        temperature: 0.1,
        messages: [
          {
            role: "system",
            content:
              "You are a professional translator. Output only valid JSON with no markdown, no explanation, no extra text.",
          },
          { role: "user", content: prompt },
        ],
      }),
    },
  );

  const data = await response.json();
  if (!data.choices?.[0]?.message?.content)
    throw new Error(`API error: ${JSON.stringify(data)}`);
  let text = data.choices[0].message.content.trim();
  text = text
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "");
  return JSON.parse(text);
}

async function main() {
  if (
    !OPENROUTER_API_KEY ||
    OPENROUTER_API_KEY === "YOUR_OPENROUTER_API_KEY_HERE"
  ) {
    console.error("ERROR: Set your OpenRouter API key first:");
    console.error(
      "  Edit translate_all.mjs line 5 and replace YOUR_OPENROUTER_API_KEY_HERE with your actual key",
    );
    process.exit(1);
  }

  const langs = Object.entries(LANGUAGES);
  const files = Object.keys(EN_FILES);
  console.log(
    `Translating ${files.length} files x ${langs.length} languages = up to ${files.length * langs.length} API calls\n`,
  );

  let ok = 0,
    skipped = 0,
    failed = 0;

  for (const [code, name] of langs) {
    console.log(`\n[${code}] ${name}`);
    for (const file of files) {
      const filePath = path.join(LOCALES_DIR, code, file);
      if (!fs.existsSync(filePath)) {
        console.log(`  ${file} — SKIP (not found)`);
        skipped++;
        continue;
      }
      process.stdout.write(`  ${file}... `);
      try {
        const translated = await translateFile(EN_FILES[file], code, name);
        fs.writeFileSync(
          filePath,
          JSON.stringify(translated, null, 2) + "\n",
          "utf8",
        );
        console.log("OK");
        ok++;
      } catch (err) {
        console.log(`FAIL — ${err.message.slice(0, 100)}`);
        failed++;
      }
      // Small delay to avoid rate limits
      await new Promise((r) => setTimeout(r, 400));
    }
  }

  console.log(`\n${"=".repeat(50)}`);
  console.log(`Done. ${ok} translated, ${skipped} skipped, ${failed} failed.`);
  if (failed > 0)
    console.log(
      "Re-run the script to retry failed files — it will overwrite with correct data.",
    );
}

main();
