import { useState } from "react";
import { cn } from "@/frontend/theme/tokens";
import { Shield, AlertTriangle, CheckCircle2, Clock, Users, TrendingUp, Star, Eye, ChevronRight, Building2, Heart, ChevronDown } from "lucide-react";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services";
import { PageSkeleton } from "@/frontend/components/shared/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function AdminPlacementMonitoringPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.adminPlacementMonitoring", "Admin Placement Monitoring"));

  const [expandedPlacement, setExpandedPlacement] = useState<string | null>(null);
  const { data: placements, loading: pL } = useAsyncData(() => adminService.getPlacements());
  const { data: agencyPerformance, loading: aL } = useAsyncData(() => adminService.getAgencyPerformance());
  const { data: alerts, loading: alL } = useAsyncData(() => adminService.getAlerts());

  if (pL || aL || alL || !placements || !agencyPerformance || !alerts) return <PageSkeleton cards={4} />;

  const activePlacementCount = placements.filter(p => p.status === "active").length;
  const shiftsToday = placements.filter(p => p.status === "active").length * 2;
  const avgMissed = placements.length > 0 ? placements.reduce((s, p) => s + p.missedShifts, 0) / placements.length : 0;
  const incidentRate = (avgMissed * 2).toFixed(1);
  const avgRating = placements.length > 0
    ? (placements.reduce((s, p) => s + p.rating, 0) / placements.length).toFixed(1)
    : "0.0";

  return (
    <>
      <div className="space-y-6">
        <div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: cn.purpleBg }}><Shield className="w-5 h-5" style={{ color: cn.purple }} /></div><div><h1 className="text-xl" style={{ color: cn.text }}>Placement Monitoring</h1><p className="text-sm" style={{ color: cn.textSecondary }}>Platform-wide care placement oversight</p></div></div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{ label: "Active Placements", value: String(activePlacementCount), icon: Shield, color: cn.purple, bg: cn.purpleBg }, { label: "Shifts Today", value: String(shiftsToday), icon: Clock, color: cn.teal, bg: cn.tealBg }, { label: "Incident Rate", value: `${incidentRate}%`, icon: AlertTriangle, color: cn.amber, bg: cn.amberBg }, { label: "Avg Satisfaction", value: `${avgRating} \u2605`, icon: Star, color: cn.green, bg: cn.greenBg }].map((s) => { const Icon = s.icon; return (<div key={s.label} className="stat-card"><Icon className="w-5 h-5 mb-2" style={{ color: s.color }} /><p className="text-lg" style={{ color: s.color }}>{s.value}</p><p className="text-xs" style={{ color: cn.textSecondary }}>{s.label}</p></div>); })}</div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2"><h3 className="text-sm mb-4" style={{ color: cn.text }}>Active Placements</h3>
            <div className="hidden md:block finance-card p-5"><div className="overflow-x-auto"><table className="w-full text-xs min-w-[600px]"><thead><tr style={{ color: cn.textSecondary, borderBottom: `1px solid ${cn.border}` }}><th className="text-left py-2 px-2">ID</th><th className="text-left py-2 px-2">Agency</th><th className="text-left py-2 px-2">Patient</th><th className="text-left py-2 px-2">Compliance</th><th className="text-left py-2 px-2">Rating</th><th className="text-left py-2 px-2">Missed</th></tr></thead><tbody>{placements.map((pl) => { const complianceColor = pl.compliance >= 95 ? cn.green : pl.compliance >= 85 ? cn.amber : "#EF4444"; return (<tr key={pl.id} style={{ borderBottom: `1px solid ${cn.border}` }}><td className="py-2 px-2" style={{ color: cn.text }}>{pl.id}</td><td className="py-2 px-2" style={{ color: cn.textSecondary }}>{pl.agency}</td><td className="py-2 px-2" style={{ color: cn.text }}>{pl.patient}</td><td className="py-2 px-2"><div className="flex items-center gap-1.5"><div className="w-12 h-1.5 rounded-full" style={{ background: cn.bgInput }}><div className="h-full rounded-full" style={{ width: `${pl.compliance}%`, background: complianceColor }} /></div><span style={{ color: complianceColor }}>{pl.compliance}%</span></div></td><td className="py-2 px-2" style={{ color: cn.amber }}>{pl.rating} \u2605</td><td className="py-2 px-2" style={{ color: pl.missedShifts > 2 ? "#EF4444" : cn.textSecondary }}>{pl.missedShifts}</td></tr>); })}</tbody></table></div></div>
            <div className="md:hidden space-y-3">{placements.map((pl) => { const complianceColor = pl.compliance >= 95 ? cn.green : pl.compliance >= 85 ? cn.amber : "#EF4444"; const isExpanded = expandedPlacement === pl.id; return (<div key={pl.id} className="finance-card overflow-hidden"><button onClick={() => setExpandedPlacement(isExpanded ? null : pl.id)} className="w-full p-4 flex items-center justify-between cn-touch-target text-left"><div className="flex items-center gap-3 min-w-0"><div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0" style={{ background: cn.purpleBg }}><Shield className="w-4 h-4" style={{ color: cn.purple }} /></div><div className="min-w-0"><p className="text-sm truncate" style={{ color: cn.text }}>{pl.patient}</p><p className="text-xs truncate" style={{ color: cn.textSecondary }}>{pl.agency}</p></div></div><div className="flex items-center gap-2 shrink-0"><span className="text-xs px-2 py-0.5 rounded-full" style={{ background: `${complianceColor}20`, color: complianceColor }}>{pl.compliance}%</span><ChevronDown className="w-4 h-4 transition-transform" style={{ color: cn.textSecondary, transform: isExpanded ? "rotate(180deg)" : "none" }} /></div></button>{isExpanded && (<div className="px-4 pb-4 space-y-2 text-xs" style={{ borderTop: `1px solid ${cn.borderLight}` }}><div className="flex justify-between pt-3"><span style={{ color: cn.textSecondary }}>ID</span><span style={{ color: cn.text }}>{pl.id}</span></div><div className="flex justify-between"><span style={{ color: cn.textSecondary }}>Caregiver</span><span style={{ color: cn.text }}>{pl.caregiver}</span></div><div className="flex justify-between"><span style={{ color: cn.textSecondary }}>Guardian</span><span style={{ color: cn.text }}>{pl.guardian}</span></div><div className="flex justify-between"><span style={{ color: cn.textSecondary }}>Rating</span><span style={{ color: cn.amber }}>{pl.rating} \u2605</span></div><div className="flex justify-between"><span style={{ color: cn.textSecondary }}>Missed Shifts</span><span style={{ color: pl.missedShifts > 2 ? "#EF4444" : cn.textSecondary }}>{pl.missedShifts}</span></div><div className="flex justify-between"><span style={{ color: cn.textSecondary }}>Started</span><span style={{ color: cn.text }}>{pl.start}</span></div><div className="flex justify-between items-center"><span style={{ color: cn.textSecondary }}>Compliance</span><div className="flex items-center gap-2"><div className="w-20 h-1.5 rounded-full" style={{ background: cn.bgInput }}><div className="h-full rounded-full" style={{ width: `${pl.compliance}%`, background: complianceColor }} /></div><span style={{ color: complianceColor }}>{pl.compliance}%</span></div></div></div>)}</div>); })}</div>
          </div>

          <div><h3 className="text-sm mb-3" style={{ color: cn.text }}>Alerts & Flags</h3><div className="space-y-3">{alerts.map((a, i) => (<div key={i} className="finance-card p-3" style={{ borderLeft: `3px solid ${a.severity === "critical" ? "#EF4444" : cn.amber}` }}><div className="flex items-start gap-2"><AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" style={{ color: a.severity === "critical" ? "#EF4444" : cn.amber }} /><p className="text-xs" style={{ color: cn.text }}>{a.text}</p></div></div>))}</div></div>
        </div>

        <div><h3 className="text-sm mb-4" style={{ color: cn.text }}>Agency Performance Comparison</h3>
          <div className="hidden md:block finance-card p-5"><div className="overflow-x-auto"><table className="w-full text-xs min-w-[500px]"><thead><tr style={{ color: cn.textSecondary, borderBottom: `1px solid ${cn.border}` }}><th className="text-left py-2 px-2">Agency</th><th className="text-left py-2 px-2">Active</th><th className="text-left py-2 px-2">Rating</th><th className="text-left py-2 px-2">On-Time</th><th className="text-left py-2 px-2">Incidents</th><th className="text-left py-2 px-2">Revenue</th></tr></thead><tbody>{agencyPerformance.map((a) => (<tr key={a.name} style={{ borderBottom: `1px solid ${cn.border}` }}><td className="py-2.5 px-2 flex items-center gap-2"><Building2 className="w-4 h-4" style={{ color: cn.teal }} /><span style={{ color: cn.text }}>{a.name}</span></td><td className="py-2.5 px-2" style={{ color: cn.text }}>{a.placements}</td><td className="py-2.5 px-2" style={{ color: cn.amber }}>{a.rating} \u2605</td><td className="py-2.5 px-2" style={{ color: Number(a.onTimeRate.replace('%', '')) >= 90 ? cn.green : cn.amber }}>{a.onTimeRate}</td><td className="py-2.5 px-2" style={{ color: Number(a.incidentRate.replace('%', '')) > 3 ? "#EF4444" : cn.green }}>{a.incidentRate}</td><td className="py-2.5 px-2" style={{ color: cn.text }}>{a.revenue}</td></tr>))}</tbody></table></div></div>
          <div className="md:hidden space-y-3">{agencyPerformance.map((a) => (<div key={a.name} className="finance-card p-4"><div className="flex items-center gap-2 mb-3"><Building2 className="w-4 h-4" style={{ color: cn.teal }} /><span className="text-sm" style={{ color: cn.text }}>{a.name}</span></div><div className="grid grid-cols-3 gap-3 text-center"><div><p className="text-sm" style={{ color: cn.amber }}>{a.rating} \u2605</p><p className="text-[10px]" style={{ color: cn.textSecondary }}>Rating</p></div><div><p className="text-sm" style={{ color: Number(a.onTimeRate.replace('%', '')) >= 90 ? cn.green : cn.amber }}>{a.onTimeRate}</p><p className="text-[10px]" style={{ color: cn.textSecondary }}>On-Time</p></div><div><p className="text-sm" style={{ color: cn.text }}>{a.placements}</p><p className="text-[10px]" style={{ color: cn.textSecondary }}>Active</p></div></div></div>))}</div>
        </div>
      </div>
    </>
  );
}