import { useState } from "react";
import { cn } from "@/frontend/theme/tokens";
import { CheckCircle, XCircle, Eye, FileText, Clock } from "lucide-react";
import { BottomSheet } from "@/frontend/components/BottomSheet";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services";
import { PageSkeleton } from "@/frontend/components/shared/PageSkeleton";
import type { AdminVerification } from "@/backend/models";
import { useTranslation } from "react-i18next";

const statusConfig: Record<string, { color: string; bg: string; label: string; icon: React.ElementType }> = { pending: { color: "#E8A838", bg: "#FFB54D20", label: "Pending", icon: Clock }, under_review: { color: "#7B5EA7", bg: "#8082ED20", label: "Under Review", icon: Eye }, approved: { color: "#5FB865", bg: "#7CE57720", label: "Approved", icon: CheckCircle }, rejected: { color: "#EF4444", bg: "#EF444420", label: "Rejected", icon: XCircle } };

export default function AdminVerificationsPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.adminVerifications", "Admin Verifications"));

  const { data: verifications, loading } = useAsyncData(() => adminService.getVerifications());
  const [filter, setFilter] = useState("all");
  const [selected, setSelected] = useState<AdminVerification | null>(null);

  if (loading || !verifications) return <PageSkeleton cards={4} />;

  const filtered = verifications.filter(v => filter === "all" || v.status === filter);

  return (
    <div className="space-y-5">
      <div><h1 className="text-2xl" style={{ color: cn.text }}>Verification Queue</h1><p className="text-sm" style={{ color: cn.textSecondary }}>Review and approve caregiver, agency, and shop registrations</p></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{[{ label: "Pending", value: verifications.filter(v => v.status === "pending").length, color: "#E8A838", bg: "#FFB54D20" }, { label: "Under Review", value: verifications.filter(v => v.status === "under_review").length, color: "#7B5EA7", bg: "#8082ED20" }, { label: "Approved Today", value: 7, color: "#5FB865", bg: "#7CE57720" }, { label: "Rejected", value: 2, color: "#EF4444", bg: "#EF444420" }].map(s => (<div key={s.label} className="cn-stat-card flex items-center gap-3"><div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: s.bg }}><span className="text-lg" style={{ color: s.color }}>{s.value}</span></div><p className="text-sm" style={{ color: cn.text }}>{s.label}</p></div>))}</div>
      <div className="flex gap-2 overflow-x-auto pb-1 -mx-1 px-1 scrollbar-hide">{[["all", "All"], ["pending", "Pending"], ["under_review", "Under Review"], ["approved", "Approved"], ["rejected", "Rejected"]].map(([val, label]) => (<button key={val} onClick={() => setFilter(val)} className="px-4 py-2.5 rounded-lg text-sm transition-all whitespace-nowrap shrink-0 cn-touch-target" style={{ background: filter === val ? cn.pink : cn.bgCard, color: filter === val ? "white" : cn.text, boxShadow: "0 2px 8px rgba(0,0,0,0.06)" }}>{label}</button>))}</div>
      <div className="space-y-3">{filtered.map(v => { const sc = statusConfig[v.status] ?? statusConfig.pending; const StatusIcon = sc.icon; return (<div key={v.id} className="finance-card p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 sm:gap-4"><div className="flex items-center gap-3 sm:gap-4"><div className="w-11 h-11 sm:w-12 sm:h-12 rounded-full flex items-center justify-center text-white text-lg shrink-0" style={{ background: v.color }}>{v.avatar}</div><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><p className="text-sm sm:text-base truncate" style={{ color: cn.text }}>{v.name}</p></div><div className="flex items-center gap-1.5 mt-1 flex-wrap"><span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px]" style={{ background: `${v.color}20`, color: v.color }}>{v.role}</span><span className="inline-flex items-center gap-0.5 px-2 py-0.5 rounded-full text-[10px]" style={{ background: sc.bg, color: sc.color }}><StatusIcon className="w-3 h-3" />{sc.label}</span></div><p className="text-xs mt-1" style={{ color: cn.textSecondary }}>{v.location} \u00b7 {v.specialty} \u00b7 Submitted {v.submitted}</p></div></div><div className="flex flex-wrap gap-2 shrink-0"><button onClick={() => setSelected(v)} className="flex items-center gap-1.5 px-3 py-2 rounded-lg border text-xs cn-touch-target" style={{ borderColor: cn.border, color: cn.text }}><Eye className="w-3.5 h-3.5" /> Review</button>{(v.status === "pending" || v.status === "under_review") && (<><button className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-white text-xs cn-touch-target" style={{ background: "#5FB865" }}><CheckCircle className="w-3.5 h-3.5" /> Approve</button><button className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-white text-xs cn-touch-target" style={{ background: "#EF4444" }}><XCircle className="w-3.5 h-3.5" /> Reject</button></>)}</div></div><div className="mt-3 flex flex-wrap gap-2">{v.docs.map(d => (<span key={d} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs cn-touch-target" style={{ background: cn.bgInput, color: cn.text, border: `1px solid ${cn.borderLight}` }}><FileText className="w-3 h-3" style={{ color: cn.pink }} /> {d}</span>))}</div></div>); })}</div>
      <BottomSheet open={!!selected} onClose={() => setSelected(null)} title={selected ? `Review: ${selected.name}` : ""}>{selected && (<div className="space-y-4"><div className="space-y-3">{[["Role", selected.role], ["Location", selected.location], ["Specialty", selected.specialty], ["Submitted", selected.submitted]].map(([l, v]) => (<div key={l} className="flex justify-between text-sm"><span style={{ color: cn.textSecondary }}>{l}</span><span style={{ color: cn.text }}>{v}</span></div>))}</div><div><h3 className="text-sm mb-2" style={{ color: cn.text }}>Documents Submitted</h3><div className="space-y-2">{selected.docs.map(d => (<div key={d} className="flex items-center justify-between p-3 rounded-lg" style={{ background: cn.bgInput }}><span className="flex items-center gap-2 text-sm" style={{ color: cn.text }}><FileText className="w-4 h-4" style={{ color: cn.pink }} />{d}</span><button className="text-xs" style={{ color: cn.pink }}>View</button></div>))}</div></div>{(selected.status === "pending" || selected.status === "under_review") && (<div className="flex gap-3 pt-2"><button className="flex-1 py-3 rounded-xl text-white text-sm cn-touch-target" style={{ background: "#5FB865" }}>Approve</button><button className="flex-1 py-3 rounded-xl text-white text-sm cn-touch-target" style={{ background: "#EF4444" }}>Reject</button></div>)}</div>)}</BottomSheet>
    </div>
  );
}