import { cn } from "@/frontend/theme/tokens";
import { Activity, AlertCircle, Ban, CheckCircle2, History, Lock, Mail, Phone, ShieldCheck } from "lucide-react";
import { useParams } from "react-router";
import { Button } from "@/frontend/components/ui/button";
import { PageHero } from "@/frontend/components/PageHero";
import { useAsyncData, useDocumentTitle } from "@/frontend/hooks";
import { adminService } from "@/backend/services/admin.service";
import { PageSkeleton } from "@/frontend/components/PageSkeleton";
import { useTranslation } from "react-i18next";

export default function UserInspectorPage() {
  const { t: tDocTitle } = useTranslation("common");
  useDocumentTitle(tDocTitle("pageTitles.userInspector", "User Inspector"));

  const { data: inspectorData, loading } = useAsyncData(() => adminService.getUserInspector());

  if (loading || !inspectorData) return <PageSkeleton />;

  return (
    <div>
      <PageHero gradient="radial-gradient(143.86% 887.35% at -10.97% -22.81%, #1F2937 0%, #111827 100%)" className="pt-8 pb-32 px-6"><div className="max-w-6xl mx-auto"><div className="flex justify-between items-center mb-8"><div className="flex items-center gap-4"><h1 className="text-2xl font-bold text-white">User Inspector</h1></div><div className="flex gap-2"><Button className="bg-red-500 hover:bg-red-600 text-white font-bold rounded-xl h-12 px-6 shadow-lg"><Ban className="w-4 h-4 mr-2" /> Suspend Account</Button><Button className="bg-white/10 hover:bg-white/20 text-white border border-white/20 font-bold rounded-xl h-12 px-6"><Lock className="w-4 h-4 mr-2" /> Reset Security</Button></div></div><div className="finance-card p-6 !bg-white/10 !backdrop-blur-xl !border-white/20 flex flex-col md:flex-row items-center gap-8"><div className="relative"><div className="w-24 h-24 rounded-3xl bg-white/20 flex items-center justify-center text-white text-3xl font-black ring-4 ring-white/20">{inspectorData.user.name.split(" ").map((w: string) => w[0]).join("").slice(0, 2)}</div>{inspectorData.user.verified && <div className="absolute -bottom-2 -right-2 bg-[#7CE577] text-white p-2 rounded-full border-4 border-[#111827] shadow-lg"><ShieldCheck className="w-4 h-4" /></div>}</div><div className="flex-1 text-center md:text-left"><div className="flex flex-col md:flex-row items-center gap-3 mb-2"><h2 className="text-3xl font-black text-white">{inspectorData.user.name}</h2><span className="px-3 py-1 rounded-full bg-[#EAB1C1] text-[#DB869A] text-[10px] font-black uppercase tracking-widest">{inspectorData.user.role}</span></div><div className="flex flex-wrap justify-center md:justify-start gap-6 text-white/60 text-sm font-medium"><span className="flex items-center gap-2"><Mail className="w-4 h-4" /> {inspectorData.user.email}</span><span className="flex items-center gap-2"><Phone className="w-4 h-4" /> {inspectorData.user.phone}</span><span className="flex items-center gap-2 text-[#7CE577]"><Activity className="w-4 h-4" /> Joined: {inspectorData.user.joined}</span></div></div><div className="grid grid-cols-2 gap-4 w-full md:w-auto"><div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-center"><p className="text-[10px] text-white/40 uppercase font-bold tracking-widest mb-1">Lifetime Earn</p><p className="text-xl font-black text-white">{inspectorData.user.stats.earnings}</p></div><div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-center"><p className="text-[10px] text-white/40 uppercase font-bold tracking-widest mb-1">Rating</p><p className="text-xl font-black text-[#7CE577]">{inspectorData.user.stats.rating.toFixed(1)}</p></div></div></div></div></PageHero>
      <div className="max-w-6xl mx-auto px-6 -mt-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6"><div className="finance-card p-8"><div className="flex justify-between items-center mb-8"><h3 className="text-xl font-bold text-gray-800 flex items-center gap-2"><History className="w-5 h-5 text-gray-400" />Security & Activity Audit</h3><Button variant="ghost" className="text-xs font-bold text-[#FEB4C5]">Export Audit</Button></div><div className="space-y-6 relative before:absolute before:left-5 before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-100">{inspectorData.user.recentActivity.map((log, i) => (<div key={i} className="flex gap-6 relative z-10"><div className={`w-10 h-10 rounded-full flex items-center justify-center border-4 border-white shadow-sm bg-gray-50 text-gray-400`}><Activity className="w-4 h-4" /></div><div><p className="font-bold text-gray-800 text-sm">{log.action}</p><p className="text-xs text-gray-400 mt-1">{log.detail}</p><p className="text-[10px] text-gray-300 font-bold mt-2 uppercase">{log.time}</p></div></div>))}</div></div>
          <div className="finance-card p-8"><h3 className="text-xl font-bold text-gray-800 mb-6">Financial Summary</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center"><div className="p-4 rounded-2xl bg-gray-50"><p className="text-[10px] text-gray-400 uppercase font-bold tracking-widest mb-1">Shifts</p><p className="text-xl font-black text-gray-800">{inspectorData.user.stats.shifts}</p></div><div className="p-4 rounded-2xl bg-gray-50"><p className="text-[10px] text-gray-400 uppercase font-bold tracking-widest mb-1">Lifetime Earn</p><p className="text-xl font-black text-[#5FB865]">{inspectorData.user.stats.earnings}</p></div><div className="p-4 rounded-2xl bg-gray-50"><p className="text-[10px] text-gray-400 uppercase font-bold tracking-widest mb-1">Rating</p><p className="text-xl font-black text-[#E8A838]">{inspectorData.user.stats.rating.toFixed(1)}</p></div><div className="p-4 rounded-2xl bg-gray-50"><p className="text-[10px] text-gray-400 uppercase font-bold tracking-widest mb-1">Reviews</p><p className="text-xl font-black text-gray-800">{inspectorData.user.stats.reviews}</p></div></div></div></div>
        <div className="lg:col-span-1 space-y-6"><div className="finance-card p-8 bg-red-50 border-red-100"><h3 className="font-bold text-red-700 mb-4 flex items-center gap-2"><AlertCircle className="w-5 h-5" />Moderator Action Needed</h3><p className="text-xs text-red-600 leading-relaxed mb-6">User has logged in from 3 distinct IP addresses in the last 24 hours. High risk of account sharing.</p><div className="space-y-3"><Button className="w-full bg-red-600 text-white rounded-xl h-11 font-bold shadow-lg">Lock Financials</Button><Button variant="outline" className="w-full border-red-200 text-red-600 h-11 font-bold">Contact User</Button></div></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-6">Vetting Status</h3><div className="space-y-4">{[{ label: "NID Verification", ok: true }, { label: "Police Clearance", ok: true }, { label: "Medical License", ok: true }, { label: "Phone Verification", ok: true }, { label: "Psychological Screen", ok: false }].map((v, i) => (<div key={i} className="flex justify-between items-center text-xs"><span className="text-gray-500 font-medium">{v.label}</span>{v.ok ? <CheckCircle2 className="w-4 h-4 text-[#7CE577]" /> : <AlertCircle className="w-4 h-4 text-orange-400" />}</div>))}</div><Button variant="ghost" className="w-full mt-8 text-xs font-bold text-[#FEB4C5] bg-[#FFF5F7] rounded-xl h-11">Manage Verifications</Button></div><div className="finance-card p-8"><h3 className="font-bold text-gray-800 mb-4">Support History</h3><div className="space-y-4"><div className="p-3 rounded-xl bg-gray-50 border border-gray-100 group cursor-pointer hover:border-[#FEB4C5]"><div className="flex justify-between mb-1"><p className="text-[10px] font-bold text-[#DB869A] uppercase">#TK-9921</p><p className="text-[10px] text-gray-300">Resolved</p></div><p className="text-xs font-bold text-gray-700 truncate">Payment delay in bKash transfer</p></div></div></div></div>
      </div></div>
      <style dangerouslySetInnerHTML={{ __html: ".finance-card { background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.4); border-radius: 3rem; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.03); }" }} />
    </div>
  );
}