-- ═══════════════════════════════════════════════════════════════════════
-- CareNet Seed: Public Schema (REAL DATA ONLY)
-- ═══════════════════════════════════════════════════════════════════════
-- NOTE:
--   All Mock_ demo seed rows that previously lived in public.* have been
--   moved into the demo schema migrations:
--
--     20260408100000_demo_schema_create.sql
--     20260408110000_demo_schema_seed.sql
--
--   The live database cleanup for existing Mock_ rows in public.* is handled
--   by:
--
--     20260408130000_demo_remove_public_mock_rows.sql
--
--   This file is intentionally empty and kept as a placeholder for any
--   future NON‑demo/public seed data. Do not add Mock_ demo rows here.
-- ═══════════════════════════════════════════════════════════════════════

